import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Nav-bar";
import Footer from "./Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="White-Perkox.ico" type="image/x-icon" />
      </head>
      <body>
        <Navbar />
        <Footer />
        <div className="mt-[5rem]">{children}</div>
      </body>
    </html>
  );
}
