import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Nav-bar";
import { DrawerProvider } from "@/contexts/DrawerContext";
import { DeviceProvider } from "@/contexts/DeviceContext";
import { FilterProvider } from "@/contexts/FilterContext";
import StarBackground from "./Components/StarBackground";
import { DrawerTabsProvider } from "@/contexts/DrawerTabs";
import { CardProvider } from "@/contexts/CardContext";
import { DataProvider } from "@/contexts/DataContext";
import { ErrorContextProvider } from "@/contexts/ErrorContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PERKOX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="White-Perkox.ico" type="image/x-icon" />
      </head>
      <body>
        <Navbar />
        <ErrorContextProvider>
          <DataProvider>
            <CardProvider>
              <FilterProvider>
                <DeviceProvider>
                  <DrawerTabsProvider>
                    <DrawerProvider>{children}</DrawerProvider>
                  </DrawerTabsProvider>
                  <StarBackground />
                </DeviceProvider>
              </FilterProvider>
            </CardProvider>
          </DataProvider>
        </ErrorContextProvider>
      </body>
    </html>
  );
}
