"use client";
import ButtonFilter from "./Components/ButtonFilter";

import { useEffect } from "react";
import { useDataContext } from "@/contexts/DataContext";
import DrawerDemo from "./Components/Drawer";

interface dataProps {
  name: string;
  instructions: string;
  image: string;
  os: string;
  reward: number;
  id: number;
}

export default function Home() {
  const { dataArr, setDataArr } = useDataContext();

  useEffect(() => {
    // Simulating fetching data from an API or any asynchronous operation

    const dataJ = [
      {
        id: 609,
        offer_type: "CPE",
        name: "Family Island \u2014 Farming game - iOS",
        instructions:
          "Open the app, register, play and complete level 21 within 30 days.",
        description:
          "Open the app, register, play and complete level 21 within 30 days.",
        short_description:
          "Open the app, register, play and complete level 21 within 30 days.",
        disclaimer: "This offer rewards within 24 hours. New users only.",
        image:
          "https://static.offertoro.com/uploads/offers_image/34dbbb82044ff183da8676081ffb6bbdd91abf722afd0abc3125cfe090734f3e.jpeg",
        goals: [{}, {}, {}],
        os: "ios",
        incent: "0",
        url: "https://clickwall.test/api/redirect/eyJpdiI6InRnQkQvOHhwNVNVN3lwQUt2enJFZ3c9PSIsInZhbHVlIjoiN0ZudERlOStPSUlFRWR5UDdmUW5zWWFNMGdBOUdjMFMxZ3krV20rWkdVK3AxRmtFU1VDUVh0TzBDaThHbE1mY2dvQXduTit5dTBXdCs5azFreTdjbFpxeThmMG1rdE1zTjRuMnNadkRSUHRzMGozcGFQMUhySWtpL0FDa21FdUxESUc3RTd4cVdDWERJZjZRZ1JlTnRlK3UwVnlXdkFZMEcwWmpqNVFXNTFqTTJKYkJnYUNWNXJraDFuVVNjTi9yZjVqbS9LWTZEbWR1SEZZTEp6ZVpkWW1BMDRjVy9xTElFUVBsdWFjSk4yZlFxeXZCa01rRStaaTFzWk1rei82a3dCTENXcW5YUlFVQ1B3dDYwV3l3NjJoNjVEY0NUeHlQa0tIazlzNHhXNUhEZlZWNmh1ZUNvQXFReTBVSHh5TnQ1dFBXWnNrTHlHQkE1TUNzMnVRd2VzeDZVYVVsRW9TbzNyay9nUHlvQWRvVi9zVkNQcWM2T09TcVVGT1ZaRnRDQlcxTzY2Y0ZIRDJKdmNRRUF1NkpJaldwVk5rUTVaN09ER3ZYWjg2b0NRdz0iLCJtYWMiOiJhY2ExNjIzNDdkMDRjZGMxZjgwYzU4ZWEwNzc0OTkyMTNlZGQ0ZDJhNWExMmMwMmE2Yzg3N2RlNDVhMDY2NzE5IiwidGFnIjoiIn0=",
        reward: 1400,
      },
      {
        id: 699,
        offer_type: "CPA",
        name: "iPhone 15 voucher!",
        instructions:
          "Complete sign up questionnaire and start your free trial using a valid Paypal account.",
        description:
          "Complete sign up questionnaire and start your free trial using a valid Paypal account.",
        short_description:
          "Complete sign up questionnaire and start your free trial using a valid Paypal account.",
        disclaimer: "This offer rewards within 24 hours. New users only.",
        payout: "1.62",
        image:
          "https://static.offertoro.com/uploads/offers_image/8876d31ca927823a99262d554bf4120c9c104036cdbdb4622b2461b4c55926b9.png",
        countries: [
          "AD",
          "AE",
          "AF",
          "AG",
          "AI",
          "AL",
          "AM",
          "AN",
          "AO",
          "AQ",
          "AR",
          "AS",
          "AT",
          "AU",
          "AW",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BM",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BV",
          "BW",
          "BY",
          "BZ",
          "CC",
          "CD",
          "CF",
          "CG",
          "CH",
          "CI",
          "CK",
          "CL",
          "CM",
          "CN",
          "CO",
          "CR",
          "CS",
          "CU",
          "CV",
          "CX",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "EH",
          "ER",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FK",
          "FM",
          "FO",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GF",
          "GH",
          "GI",
          "GL",
          "GM",
          "GN",
          "GP",
          "GQ",
          "GR",
          "GS",
          "GT",
          "GU",
          "GW",
          "GY",
          "HK",
          "HM",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IO",
          "IQ",
          "IR",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KP",
          "KR",
          "KW",
          "KY",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MM",
          "MN",
          "MO",
          "MP",
          "MQ",
          "MR",
          "MS",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NC",
          "NE",
          "NF",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NU",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PF",
          "PG",
          "PH",
          "PK",
          "PL",
          "PM",
          "PN",
          "PR",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RE",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SD",
          "SE",
          "SG",
          "SH",
          "SI",
          "SJ",
          "SK",
          "SL",
          "SM",
          "SN",
          "SO",
          "SR",
          "ST",
          "SV",
          "SY",
          "SZ",
          "TC",
          "TD",
          "TF",
          "TG",
          "TH",
          "TJ",
          "TK",
          "TL",
          "TM",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UM",
          "US",
          "UY",
          "UZ",
          "VA",
          "VC",
          "VE",
          "VG",
          "VI",
          "VN",
          "VU",
          "WF",
          "WS",
          "YE",
          "YT",
          "ZA",
          "ZM",
          "ZW",
        ],
        goals: null,
        os: "all",
        incent: "1",
        url: "https://clickwall.test/api/redirect/eyJpdiI6Ilo2WGFySlNzM3FmczZWZnI0R21NK2c9PSIsInZhbHVlIjoiTUJIQjJTdUtNTWtCVEpIMUdWcHJXbEJwZWozN3p2dlgzU2kvaGZoYkdHUjJXZ2xGVnNJbnFubVlTaXBoSCtSKy9RQTRNeXFZOWdxaGlWWnh0a3l2TjdDcXNnU0lWZlgyRE1xMTEyVUxkZ1NxbnAybnU0MUdYbkkyeEhjb1JqTVNaZW1KT1RSV3FzTGFCcmZMbVR2Tll2RTQ5RS9hTUVIZzJndzlEbzcxRHVOaE51MVJHNzlyQnl3WUhwa0xsKy83SnVMVzllZnlxbzNpNWpoU3BYYitzeFA0ajVlU3d0QmRONnNCOGJvUFRrVmxjYU8rbmZyNEdXdTY5NWhlMnlYcjVBRkRET0dkbGFOVTJCZTdKZnAwVHJtY25DUi9tU1h0M29saXFvL2xuWDg2VS92WUpKMTF3SlJBNkh0dk1SU3o5VTlLRTFCUVFIVXRXTkFjQTgyU1Z6TmVXNVNXQ3J4Nmt3eWNUdzVFTTRXM0NzS3ljR3gvRUVnak44RktLUVpjMFJxOTVwV3dXUHZzUWtBNFpNUnZFUT09IiwibWFjIjoiMGFjODRlNTA5MTRiZWYwN2Y4OTRmMjg5OTc2MTkzM2Y1YjA2OWNlODc3Mjg3MDBkOTBjNWI4ZjA1MTM5NjMzZiIsInRhZyI6IiJ9",
        reward: 1620,
      },
      {
        id: 860,
        offer_type: "CPE",
        name: "Brain Test: Tricky Puzzles - Android",
        instructions: "Play and reach level 250.",
        description: "Play and reach level 250.",
        short_description: "Play and reach level 250.",
        disclaimer: "This offer rewards within 24 hours. New users only.",
        payout: "0.26",
        image:
          "https://static.offertoro.com/uploads/offers_image/b20b9fbcaf6e6f38b73e47b2f25ae4faba40f8933804e719428b75157088675f.png",
        countries: [
          "BH",
          "CR",
          "DO",
          "EC",
          "EG",
          "IN",
          "PA",
          "PY",
          "RO",
          "RS",
          "RU",
          "SI",
          "SK",
          "TR",
          "UY",
        ],
        goals: null,
        os: "android",
        incent: "0",
        url: "https://clickwall.test/api/redirect/eyJpdiI6IjFqU2czQWxvTjRJYm9KZnRrNEp3bmc9PSIsInZhbHVlIjoiQXEvcU9WU1FCTjFHVmorc2Y5R0g5M0p1SnRqRitMS3JIR0hyWHBCOXljNkRiS0ljbzB3OXJXRjg5L3VESHBhem8rejRGQjk5blRkVTFNa3JjVzFsQUJhQ3lUdlRvMWxVYzhxdXBTS2VqREdDY3lQODJobEpOZDNIc1lBUU5VTU42ejUwYU4yZTdvbjZHdG1tSzNQZlYzR1hKWnU2U2pCbTJvVXh0MGtKdkk5ZVRnU084UElRTm5aa3lleEhtNmNVUkpKWlo2RXpoWno5YnRPYWNPUTNTRnQ2WGdtYkY3MDEvQkk1S1RMcDY0LzRWUjRyUVdRWWFKL3BRMURVK1RKQStBQStKTWcrTU1yLy92NWhzU0hNUXNHU2t4Mml6ZmZOekRpTndDZjVPaU1GUnprQWJtOExJK1AyU0drZnA4S1hHbDRUb1FYeElPdE5BSlJDTzZ3b1J1ZTR4RUxtL0ovd1VlL0VkTkxmb2w2eWlLa0JoclRsTzlXaWVOcFdDbEZnemVOL3AwaFV0TFJWd1loaUZnYXhXYUpZUU5reXB3NldySVQxSTU5VEtFYz0iLCJtYWMiOiI1NzNhYmU2ZDJmOGE5NGJhMjgwZjM5MzkwNTY1MWJiYzc2OGE1OTgyZDUxNmI5OTFjOThkZDZmNDM3M2QzNmI2IiwidGFnIjoiIn0=",
        reward: 260,
      },
      {
        id: 1015,
        offer_type: "CPE",
        name: "Trump's Empire - Android",
        instructions: "Play the game and build a Florida private club.\r ",
        description:
          "Play the game and build a Florida private club.\r \r This offer can be completed up to 10x faster with in-game purchases.",
        short_description:
          "Play the game and build a Florida private club.\r \r This offer can be completed up to 10x faster with in-game purchases.",
        disclaimer: "This offer rewards within 24 hours. New users only.",
        payout: "0.14",
        image:
          "https://static.offertoro.com/uploads/offers_image/0b7726f3f23aa374fdf434833c3fc5cc28a654a648ce86ed0aded02def2d7bac.jpg",
        countries: [
          "AD",
          "AE",
          "AF",
          "AG",
          "AI",
          "AL",
          "AM",
          "AN",
          "AO",
          "AQ",
          "AS",
          "AT",
          "AU",
          "AW",
          "AZ",
          "BA",
          "BB",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BM",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BV",
          "BW",
          "BZ",
          "CA",
          "CC",
          "CD",
          "CF",
          "CG",
          "CH",
          "CI",
          "CK",
          "CL",
          "CM",
          "CN",
          "CO",
          "CR",
          "CS",
          "CU",
          "CV",
          "CX",
          "CY",
          "CZ",
          "DJ",
          "DK",
          "DM",
          "DO",
          "EC",
          "EE",
          "EG",
          "EH",
          "ER",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FK",
          "FM",
          "FO",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GF",
          "GH",
          "GI",
          "GL",
          "GM",
          "GN",
          "GP",
          "GQ",
          "GR",
          "GS",
          "GT",
          "GU",
          "GW",
          "GY",
          "HK",
          "HM",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IO",
          "IQ",
          "IR",
          "IS",
          "IT",
          "JM",
          "JO",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KP",
          "KR",
          "KW",
          "KY",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MM",
          "MN",
          "MO",
          "MP",
          "MQ",
          "MR",
          "MS",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NC",
          "NE",
          "NF",
          "NG",
          "NI",
          "NL",
          "NO",
          "NR",
          "NU",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PF",
          "PG",
          "PH",
          "PL",
          "PM",
          "PN",
          "PR",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RE",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SD",
          "SE",
          "SG",
          "SH",
          "SI",
          "SJ",
          "SK",
          "SL",
          "SM",
          "SN",
          "SO",
          "SR",
          "ST",
          "SV",
          "SY",
          "SZ",
          "TC",
          "TD",
          "TF",
          "TG",
          "TH",
          "TJ",
          "TK",
          "TL",
          "TM",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UG",
          "UM",
          "UY",
          "UZ",
          "VA",
          "VC",
          "VE",
          "VG",
          "VI",
          "VN",
          "VU",
          "WF",
          "WS",
          "YE",
          "YT",
          "ZA",
          "ZM",
          "ZW",
        ],
        goals: null,
        os: "android",
        incent: "0",
        url: "https://clickwall.test/api/redirect/eyJpdiI6IkxLTjJPZHJqd0FsQ2l4S3RQQzJZUUE9PSIsInZhbHVlIjoibTltczB1dmlaL1dCaUo5YXhid2VFa3hUNkcwYml1UWlaVzVlbHlCVmxrY3RRUHY5VjhRV3V4MVo4TlJUdkNFMWtLTEd3TUd5VEs2ZnRKMUU1UmY5NW1sT0F2RGZwN3RGTlVwSXBwb3ZMTTVJQnl5aEJZZWs2dkxLUVZ3dnlJVCtEdXFQQm9RcnI4NFlqMTNSbVIwZEprQXpsaDByZ3ZjK0hFOE5iNVV4ZXNQaVl5TWhrZDFwMXRwUkFramFHMUtOMzVxRTVEdHBrR1djSVRoSzl3cC9ZSkxDWURLbHhleTE3VW01QjRSZ25Weit2WDdmTTNyVG9EbDJMbnpIUjYyNlpIZTZCS2lpSlB5NFh4Vytqbml6TWZVSHpvMzZtMHJ6OC9WdW9PYWExaHRzS21ySy85NGRZU0hSU2pLRit5WEV3MDhBUWRmZGlHQnJEZ3JKc1ZmQUZNMm5qdjgrWFo0NW5zVGpHMjQyTWJubTE4WjZka212VlJabHNXSzk3YzM3eURBcVZCVW9tUml1bzVSQ1VyZkFQUT09IiwibWFjIjoiNDQ4ZWZjNDQyYTQ0ZTZmZWQ1Mzc4OTg3NzRjNTcwODVjM2U1NDY2NjA0M2MxZDZjMWIzMzU3YjdlZDI1N2FjNCIsInRhZyI6IiJ9",
        reward: 140,
      },
      {
        id: 1041,
        offer_type: "CPE",
        name: "Donald's Empire - iOS",
        instructions: "Play the game and build a Florida private club.\r ",
        description:
          "Play the game and build a Florida private club.\r \r This offer can be completed up to 10x faster with in-game purchases.",
        short_description:
          "Play the game and build a Florida private club.\r \r This offer can be completed up to 10x faster with in-game purchases.",
        disclaimer: "This offer rewards within 24 hours. New users only.",
        payout: "0.27",
        image:
          "https://static.offertoro.com/uploads/offers_image/0b7726f3f23aa374fdf434833c3fc5cc28a654a648ce86ed0aded02def2d7bac.jpg",
        countries: [
          "AD",
          "AE",
          "AF",
          "AG",
          "AI",
          "AL",
          "AM",
          "AN",
          "AO",
          "AQ",
          "AR",
          "AS",
          "AW",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BM",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BV",
          "BW",
          "BY",
          "BZ",
          "CC",
          "CD",
          "CF",
          "CG",
          "CH",
          "CI",
          "CK",
          "CL",
          "CM",
          "CN",
          "CO",
          "CR",
          "CS",
          "CU",
          "CV",
          "CX",
          "CY",
          "CZ",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "EH",
          "ER",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FK",
          "FM",
          "FO",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GF",
          "GH",
          "GI",
          "GL",
          "GM",
          "GN",
          "GP",
          "GQ",
          "GR",
          "GS",
          "GT",
          "GU",
          "GW",
          "GY",
          "HK",
          "HM",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IO",
          "IQ",
          "IR",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KP",
          "KR",
          "KW",
          "KY",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MM",
          "MN",
          "MO",
          "MP",
          "MQ",
          "MR",
          "MS",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NC",
          "NE",
          "NF",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NU",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PF",
          "PG",
          "PH",
          "PK",
          "PL",
          "PM",
          "PN",
          "PR",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RE",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SD",
          "SE",
          "SG",
          "SH",
          "SI",
          "SJ",
          "SK",
          "SL",
          "SM",
          "SN",
          "SO",
          "SR",
          "ST",
          "SV",
          "SY",
          "SZ",
          "TC",
          "TD",
          "TF",
          "TG",
          "TH",
          "TJ",
          "TK",
          "TL",
          "TM",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UM",
          "UY",
          "UZ",
          "VA",
          "VC",
          "VE",
          "VG",
          "VI",
          "VN",
          "VU",
          "WF",
          "WS",
          "YE",
          "YT",
          "ZA",
          "ZM",
          "ZW",
        ],
        goals: null,
        os: "ios",
        incent: "0",
        url: "https://clickwall.test/api/redirect/eyJpdiI6ImJzKzZKdzhvY0JRQWFKU3VXa2IyeEE9PSIsInZhbHVlIjoibEczMlVIVjZiUkMza3NwUFVXYzJIYlkzRjhMVGVhOXlEb1pURDg0Wndmd1pwRklXUmlubzZ4NzBMRzA0TDVFeE16cGNmVkhUOXBRKzEvb0MwcWx3VVE1a011Wk5QSFA5T1lMdk93dUdxeDYyMU1BVktOd3h1ZDV1amgzTS9OTEJDUE4wM2krS3E4RjN5Y3dBY25JNjRIbTVNc0QzeHN4R2taV0ZWTGNYbjN1MDhYalJVYTdEcjBQNVorNmtveUgzRWVrOVkxR0JaSU1SSGxzN096TmlnNDN6ZG11OFdyZ21GSFZ0VmtCeTJnR1oyVlhaNjFwd3pvTHFmMk05cmZjUU1lRVlJZjBTUEtPOVIvdFpMR3F0UGdJcUZrYmZkR3R4eDJTMEpTQ05remJlN1p4eDFOdldmY0UzMTVTTjg1ajNiK25QbGRJY2ZvUTJjTHJFZ293RU9nSFdLN2hjRWxUaUZjcWpzK2tVUm5VOWx4VU8wVWRNbklPVUVVVmlGbURBQ0lWWkQyOTNjTmtzOEp2b05vMndMdz09IiwibWFjIjoiYWUxYjgwZTM4ZDQyNjE2Nzk4ZmNhZmM0YWI1NzkyZGRmYmVjZmNiNTI3MzBkYWViZDI5MGJkYWFiZmQ5MjdiNiIsInRhZyI6IiJ9",
        reward: 270,
      },
      {
        id: 1082,
        offer_type: "CPE",
        name: "Idle Lumber Empire - iOS",
        instructions: "Open and reach Factory 8 within 9 days.",
        description: "Open and reach Factory 8 within 9 days.",
        short_description: "Open and reach Factory 8 within 9 days.",
        disclaimer: "This offer rewards within 24 hours. New users only.",
        payout: "1.35",
        image:
          "https://static.offertoro.com/uploads/offers_image/bd08e484caaa603be9829d4891d5b2ca7f8436216257e413d5cadd89f0bd4f96.png",
        countries: [
          "AD",
          "AE",
          "AF",
          "AG",
          "AI",
          "AL",
          "AM",
          "AN",
          "AO",
          "AQ",
          "AR",
          "AS",
          "AT",
          "AU",
          "AW",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BM",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BV",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CC",
          "CD",
          "CF",
          "CG",
          "CH",
          "CI",
          "CK",
          "CL",
          "CM",
          "CN",
          "CO",
          "CR",
          "CS",
          "CU",
          "CV",
          "CX",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "EH",
          "ER",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FK",
          "FM",
          "FO",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GF",
          "GH",
          "GI",
          "GL",
          "GM",
          "GN",
          "GP",
          "GQ",
          "GR",
          "GS",
          "GT",
          "GU",
          "GW",
          "GY",
          "HK",
          "HM",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IO",
          "IQ",
          "IR",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KP",
          "KR",
          "KW",
          "KY",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MM",
          "MN",
          "MO",
          "MP",
          "MQ",
          "MR",
          "MS",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NC",
          "NE",
          "NF",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NU",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PF",
          "PG",
          "PH",
          "PK",
          "PL",
          "PM",
          "PN",
          "PR",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RE",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SD",
          "SE",
          "SG",
          "SH",
          "SI",
          "SJ",
          "SK",
          "SL",
          "SM",
          "SN",
          "SO",
          "SR",
          "ST",
          "SV",
          "SY",
          "SZ",
          "TC",
          "TD",
          "TF",
          "TG",
          "TH",
          "TJ",
          "TK",
          "TL",
          "TM",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UM",
          "UY",
          "UZ",
          "VA",
          "VC",
          "VE",
          "VG",
          "VI",
          "VN",
          "VU",
          "WF",
          "WS",
          "YE",
          "YT",
          "ZA",
          "ZM",
          "ZW",
        ],
        goals: null,
        os: "ios",
        incent: "0",
        url: "https://clickwall.test/api/redirect/eyJpdiI6Ik85bDgrSkphZGZzcC9GWE5ldWVoK1E9PSIsInZhbHVlIjoiZHBsS3BWWGtpZ1g5NlVWaDJML3hob1dSZlRsQ0lrVGV3a1Vnck5lZHF6bnhNVmVhNnFpSXUrdkpTaThvbm5lSWc2cml1V0Zjc0FDbG9md3ZNWTVMZllYaCtkd3ZzNWdEOUMzZHZNN0VvOHUweWZnT2VrQzcvSmFuMi8vWm1aS2NPdm90RXZYU2xVdEVHQm1haWphNHRVWUdVOWpOeTR2dDNXa1VRaTlDMHNsV2JXTzZKUHR4eDV3eFZON1JFcWpFTE9ldGdFOHY0STU3R1ZTVFlsYUZjVC9OaC84T2kycThFcWJZWUNjSllmbnhpMGpQKytsRDNTeWsvWlZVVnVpVXJabjZqMHErcFEyYUQyU0ZJZ0RSOXh0NjhBZWJKWm5QeDJFSGorYXhuMVZKQTE0cVNuOE5vSjBtYzBZVDhMSU5nL1pWd0lUY3NEVGxZZVRkV29NQUozY3MrNW00UTFxMXBwTVVSTmhWZFh0UHF0V3J3cEx2UDVJRFlXK2Q0RG1oemI5Y2tUdDdSLzkvaElCMDdIQWdIZz09IiwibWFjIjoiMmM4ZThmZTg4NjU1YzdmYmM2YzZjNGJiZmQ4YjM3YzcyYzI1N2JmMWUyODc4NjcxNTk1ZWY1NTc1NjQwYjcyYyIsInRhZyI6IiJ9",
        reward: 1350,
      },
      {
        id: 1405,
        offer_type: "CPI",
        name: "FAB Mobile Banking - iOS",
        instructions: "Open and use the app.",
        description: "Open and use the app.",
        short_description: "Open and use the app.",
        disclaimer: "This offer rewards within 24 hours. New users only.",
        payout: "0.12",
        image:
          "https://static.offertoro.com/uploads/offers_image/ada823a4eecf77e58c6559c57ddb2500b820523eb5c693a0e4e230c716d87c4b.jpeg",
        countries: ["EG", "MY"],
        goals: null,
        os: "ios",
        incent: "0",
        url: "https://clickwall.test/api/redirect/eyJpdiI6IitiQ0tHMXFscVExTmNhZzFwaDZQckE9PSIsInZhbHVlIjoiUy9hYXFibjc2dzBMbkNXR3Urc0Nkc1NJR2RwNWIzUVEyWlg5TVN3YzhZSXVBMzU4SW1rME5TKzExQkZWcHFUWE1pMU5pQXNqdm5GSHNLZjJvNGpHVzlUaVorUG9lRTJuMjIyOTBPL1QvMlQwVkxQVnBlRlp5OGZMZFl0ZUJQeHRwOExFcUQzNWhGVDE1ZkczcXhPaG9QcUxka2E1YzBkYkhPd1pMODlKNE9ycW5NN2J3cDBUZWJDM2RWWTVvMmlyNWVXNG1WSFFTbHhLQXhBVTFNeVhtMjdPK3MvNG9KWFJaeFZ5OHNQaUNkNmEzcW9laEZ5UHZLM1RoemlEUlJrMWZjcDhTQTArZC82N2pUNXBSV1UrWENPcTlzSEdhZ01PRW9FRTdWVUhRRDh5cThsRytScEpLMWNnYjBhVkVMNnV3c3NXRlhmWnRxV1A0ZTZPOVg5SUpjUWVCY1JNVWFRZi9IeXRVWU9qZ2VoUkhtY3ZDVHk2VitMamFJWXRIRlh2YXRUaEVpeDkrR1E1V1RkaC8vMEZPUT09IiwibWFjIjoiYzMxNzkwYjdiNTY0OWFhZGJmYmVhMjE0ZmRjMDM2NjgzNjAyOWU2Yzk4OWUyMzM1M2Q1Mzg5NmRhMDUwNWNmNSIsInRhZyI6IiJ9",
        reward: 120,
      },
      {
        id: 1423,
        offer_type: "CPE",
        name: "Idle Western Cowboy - Android",
        instructions: "Play the game and reach level 30.",
        description: "Play the game and reach level 30.",
        short_description: "Play the game and reach level 30.",
        disclaimer: "This offer rewards within 24 hours. New users only.",
        payout: "0.21",
        image:
          "https://static.offertoro.com/uploads/offers_image/076d76336b4c3169a2264d5a75266161e552bcff2df29161d43c38c821241171.png",
        countries: [
          "AE",
          "BR",
          "EG",
          "HK",
          "ID",
          "IL",
          "MY",
          "PH",
          "PL",
          "QA",
          "SA",
          "TH",
          "TR",
        ],
        goals: null,
        os: "android",
        incent: "0",
        url: "https://clickwall.test/api/redirect/eyJpdiI6InNISVRWejNpeHEyNVVUSUtlN1FRaUE9PSIsInZhbHVlIjoiUHpLd2M4TFJLckdDNVFUZlN6cFE3M3NwRTFUSTZTRnJRTUE4T29VZ3o2cUlneHNkNVV6cTJJejRDNzVRR3BaZEU4UnF1YlVPa1hSWXFveTBjV2ZyaGNUSGdRa080YngxT2k3L1gvYm9qb3BGSXNyK0xkWno1ODRQV05kbDgvM1JJTHd0Wm5NVEhNcTNrTmtyOEpuNWFhd2FRSzR0QnhXZFN5OUJqNGRzMXB2Mm9acXg3WVBHUXh3eHBHVEFRazVCQm0vU3N5Ri9DTGFvMlpxNVhLRzJGK2cxTzBrcjh4NUxwc3RZaW91VjZVVFBCcXBsK2xWWUwzYjAzK3FQcEFIeTN2RTBhYlEwbU1XU0VHL3RsS05NZUlJTGJIeDZMR1JBTkNWelFNMXNFV0h2LzdWM0Nla3owTE1QNXIxQnhodThqaE9mZVpmdi9xUFByZ3dpQk95OGF3YlFMRHZMbDVyRFN0RENhblZra1h0c3lhWVQ4bS90Vk5qVDhXNjYxeXJLUGpucWg0UWJDZHU3dFVyRG9wbEZMbzFzbk0zV2lSZGJKR0R5eDJyUnVTdz0iLCJtYWMiOiJhY2U0OTZlMzNjN2U2NjhkM2U0OTMwNjAzNGUyZjhlZGUzNTgyMTA0MmQ2MDdmNDJmNzIzNzYxODAwMWVhYjgyIiwidGFnIjoiIn0=",
        reward: 210,
      },
      {
        id: 1496,
        offer_type: "CPE",
        name: "Block King: Woody Puzzle Game - iOS",
        instructions:
          "Play and reach level 401 in sort puzzle mode within 10 days.",
        description:
          "Play and reach level 401 in sort puzzle mode within 10 days.",
        short_description:
          "Play and reach level 401 in sort puzzle mode within 10 days.",
        disclaimer: "This offer rewards within 24 hours. New users only.",
        payout: "0.70",
        image:
          "https://static.offertoro.com/uploads/offers_image/a016cd948550e200598928b7979d7449ff9407044695291b7f4b1cade9d2e852.jpg",
        countries: [
          "AD",
          "AE",
          "AF",
          "AG",
          "AI",
          "AL",
          "AM",
          "AN",
          "AO",
          "AQ",
          "AR",
          "AS",
          "AT",
          "AW",
          "AZ",
          "BA",
          "BB",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BM",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BV",
          "BW",
          "BY",
          "BZ",
          "CC",
          "CD",
          "CF",
          "CG",
          "CH",
          "CI",
          "CK",
          "CL",
          "CM",
          "CN",
          "CO",
          "CR",
          "CS",
          "CU",
          "CV",
          "CX",
          "CY",
          "CZ",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "EH",
          "ER",
          "ET",
          "FI",
          "FJ",
          "FK",
          "FM",
          "FO",
          "GA",
          "GD",
          "GE",
          "GF",
          "GH",
          "GI",
          "GL",
          "GM",
          "GN",
          "GP",
          "GQ",
          "GR",
          "GS",
          "GT",
          "GU",
          "GW",
          "GY",
          "HK",
          "HM",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IO",
          "IQ",
          "IR",
          "IS",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KP",
          "KR",
          "KW",
          "KY",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MM",
          "MN",
          "MO",
          "MP",
          "MQ",
          "MR",
          "MS",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NC",
          "NE",
          "NF",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NU",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PF",
          "PG",
          "PH",
          "PL",
          "PM",
          "PN",
          "PR",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RE",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SD",
          "SE",
          "SG",
          "SH",
          "SI",
          "SJ",
          "SK",
          "SL",
          "SM",
          "SN",
          "SO",
          "SR",
          "ST",
          "SV",
          "SY",
          "SZ",
          "TC",
          "TD",
          "TF",
          "TG",
          "TH",
          "TJ",
          "TK",
          "TL",
          "TM",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UM",
          "UY",
          "UZ",
          "VA",
          "VC",
          "VE",
          "VG",
          "VI",
          "VN",
          "VU",
          "WF",
          "WS",
          "YE",
          "YT",
          "ZA",
          "ZM",
          "ZW",
        ],
        goals: null,
        os: "ios",
        incent: "0",
        url: "https://clickwall.test/api/redirect/eyJpdiI6Im8rSnpxZk1FVVdpenRTemI5aUh4NVE9PSIsInZhbHVlIjoiRnM2Sm96cEY0WHM1OTV4ak81L0wzNG8xSk9QSCtvamxNUlhCV2ErWnNLNTE5Q1ZueDBSby96T1BCSFFpSHAwcVlXNW5WcVdZaTRtaUxuVVdHdmM4YTVJZitidDk5NTZxK3ZFU0RHbk0wMDJsd0RYWVdKejBPM3ZJUE9xVUY2N2JFVXM5Q0xOaWh1clpVNFZrcjREY2Q5V0VRaTg4dmpNakIxLzlyZTFwV29XQU1qSjdiMGRjQ1poaEIxWEdhVHFKZEtDajFCNlBJdUtTMEZycTUzcEtrQmFhQWJwQ3pLMzM3VTZOUlBXdlYxY3lJcVd3R0JzanJseHNKM1pDZlVUMk5JQW42MmNDVFNUWDIvUzc3NTFTZjNoanN2ZXBqbllNbDArQnhFMlFrd01MSncxcTRuenZmMlQ2RElGRDQvZ1ZULzcxdWRlMklOK3VBc2N6V2RRaHRvMmZ0K2xkS1hmNm11Zms3Tnp6c2tZTmtTRTZpNWR0T2gxMWRQV0E5dGU5N1B3eklGcGN5ZjRHbUw2SlVseUZqV2dDTDBFWVB4VDlEd3MxczdzMWRIOD0iLCJtYWMiOiI4NTRiYWZhMjljYmZhMDI1ZGNmMWUzNTdlNWJmOWVjMWQxZTE3ZDAxYTgyNDk1ZDU2MGY4MGE0NzM5ZTQ4MTY5IiwidGFnIjoiIn0=",
        reward: 700,
      },
      {
        id: 1499,
        offer_type: "CPE",
        name: "Diamond City - Android",
        instructions:
          "Build Cyber Mall! Play the game and construct Cyber Mall. \r ",
        description:
          "Build Cyber Mall! Play the game and construct Cyber Mall. \r \r New users only.",
        short_description:
          "Build Cyber Mall! Play the game and construct Cyber Mall. \r \r New users only.",
        disclaimer: "This offer rewards within 24 hours. New users only.",
        payout: "0.14",
        image:
          "https://static.offertoro.com/uploads/offers_image/51d7835666227937629e2dce9ecd7177ff37c74325140df5a22bcb6752a4ddc7.png",
        countries: [
          "AD",
          "AE",
          "AF",
          "AG",
          "AI",
          "AL",
          "AM",
          "AN",
          "AO",
          "AQ",
          "AR",
          "AS",
          "AT",
          "AU",
          "AW",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BM",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BV",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CC",
          "CD",
          "CF",
          "CG",
          "CH",
          "CI",
          "CK",
          "CL",
          "CM",
          "CN",
          "CO",
          "CR",
          "CS",
          "CU",
          "CV",
          "CX",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "EH",
          "ER",
          "ET",
          "FI",
          "FJ",
          "FK",
          "FM",
          "FO",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GF",
          "GH",
          "GI",
          "GL",
          "GM",
          "GN",
          "GP",
          "GQ",
          "GR",
          "GS",
          "GT",
          "GU",
          "GW",
          "GY",
          "HK",
          "HM",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IO",
          "IQ",
          "IR",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KP",
          "KR",
          "KW",
          "KY",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MM",
          "MN",
          "MO",
          "MP",
          "MQ",
          "MR",
          "MS",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NC",
          "NE",
          "NF",
          "NI",
          "NL",
          "NO",
          "NR",
          "NU",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PF",
          "PG",
          "PH",
          "PL",
          "PM",
          "PN",
          "PR",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RE",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SD",
          "SE",
          "SG",
          "SH",
          "SI",
          "SJ",
          "SK",
          "SL",
          "SM",
          "SN",
          "SO",
          "SR",
          "ST",
          "SV",
          "SY",
          "SZ",
          "TC",
          "TD",
          "TF",
          "TG",
          "TH",
          "TJ",
          "TK",
          "TL",
          "TM",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UG",
          "UM",
          "UY",
          "VA",
          "VC",
          "VG",
          "VI",
          "VN",
          "VU",
          "WF",
          "WS",
          "YE",
          "YT",
          "ZA",
          "ZM",
          "ZW",
        ],
        goals: null,
        os: "android",
        incent: "0",
        url: "https://clickwall.test/api/redirect/eyJpdiI6IjJXeDM4VEppLzVuRnlJeTVWQXlKY3c9PSIsInZhbHVlIjoiUFdUajlhM1diOVpzY3g1TVRPZ1hsdUVzMjFObk05dktHMDYyTDdiK1JCQjd5Y2Uzell3Wm5YMDBaa0syUXR0R1lMdmJBaFAyaE5odm10RkNrSkRIYXhYdVNVUktBTnhLd09YRmtJRTR2d1RFYVRhZDdrSTh0Q05VUEdwSzNUWjZrOG1nR21XNzZPcVo5MjRJVktZM0syMGRCWFBhZklzYlVUMHJCM1Fqc3ArWUs0S2xkYS9aQnFHUndUK0huVjF1QWhDcVlHNGlyWnVBUWMxS0NkOWx3TGpPTlErNFd0UkdoWHI5WFNXNGcxam5IOTFtRHR5dWMwWXNEYVJ1R1N3b1JWYWJqUyttdHBCNHhMTldrMnpGMk5ZejFGWGIrNzM0MUxKWVlQRmNqd1g3L21vTi9BNHRCdk9GbGtHb2w4OUhtR2xib1g0b2JSMWNGTHUxajg3c1ZSRE1Oc3ZVQVpMVHRLajZ2L2tSMGxvMlY1R3FYamt1MkZiRThNL1hIeUExdWdjY05iUThLVjVPSGJzNlJNWnVkUT09IiwibWFjIjoiZjhlNDk2YTU5NmJjNzZiZjIwMTY3ZjRjMWM1OGRlNjgyNmYxZTRiNzYyYjAxZTE2OTlkZTBkZTMwZTk3Y2IyNCIsInRhZyI6IiJ9",
        reward: 140,
      },
      {
        id: 1508,
        offer_type: "CPE",
        name: "GCLoot - Join & earn 2500 points",
        instructions:
          "Sign up to GCloot using full valid details and collect 2500 points.",
        description:
          "Sign up to GCloot using full valid details and collect 2500 points.\r \r Credited within 5 minutes.",
        short_description:
          "Sign up to GCloot using full valid details and collect 2500 points.\r \r Credited within 5 minutes.",
        disclaimer: "Credited within 5 minutes.",
        payout: "1.62",
        image:
          "https://static.offertoro.com/uploads/offers_image/dd4df6141077058d3e900bed3aec1ab4b4a30f401e773299e34373a2abdf04a7.png",
        countries: [
          "BR",
          "CL",
          "CO",
          "CR",
          "EG",
          "KE",
          "MO",
          "MX",
          "MY",
          "OM",
          "PE",
          "PH",
          "QA",
          "TH",
          "TR",
          "TW",
          "ZA",
        ],
        goals: null,
        os: "all",
        incent: "1",
        url: "https://clickwall.test/api/redirect/eyJpdiI6InVRTTZqRnBvSzI5d1A5bkJHKzBvaHc9PSIsInZhbHVlIjoiMHVYUjdvdlMxUnZjRWlSendWdUxlQUt1TVZ2SlVqRVhlUnVyRVlMbkZjZkpKaHFJdnIvdnpGVWgxc25MZHBnZk9BZXFrZXJSQUJSVmNQY3p2OW93V2x6dGxhTVVkcWFXWk0vZ3ZRcWN5MnBiNjFGUE1hS2VaNE5YQ1RuRTY5a3htMkpuL29OQi81Y0R4ejBHZWNyejF1NmM1cmhzb1pFdTN5dEFDY1IyTDhPV1oxeTlWYmJCWHZ5N053bFdld0RwOHd4WHRzVFZoZzFYUVF6RlpxdEt3enlCRm45RlRsR1FoV29LeGV6MHkrMkQvaEhYTWhvN3VRWVdXVk1uNHdHQU5TaG1rUS9Pc00yWkI2ZmZid2s3ZlBvYlB2Uk5lL2pnQzdXZGNaTmd6Y05tYk9xS20xc0pYYXl2eHlMR0djOGlFUEloQ3AwZnM1bVlWRXN5Wm9rZzY3d3BmYjZWNlMrTnJseWNPeGNMVmhjZzB3RmU2UW9FOCtyaE90V2FBcUl4M040NkJmMVpESzMrNnZ2dlhzT3BhWGRIaHM5ZEJ2N1VUTFUwWGR5cnRSbz0iLCJtYWMiOiJmNWU3NTU5MGZjY2NjYjQwYzRmN2VhMDQyNjY0MzM5NDhmZGU5MWZlMzQ0MTUwYjM2Nzk1MGM3NmZkZDA0MGRlIiwidGFnIjoiIn0=",
        reward: 1620,
      },
      {
        id: 1698,
        offer_type: "CPE",
        name: "GrabPoints - Complete Offers & Get Paid",
        instructions:
          "Register to Grabpoints using full valid details and collect 2500 points.",
        description:
          "Join & complete surveys, task to earn points.\r \r Register to Grabpoints using full valid details and collect 2500 points.\r \r Credited within 5 minutes.",
        short_description:
          "Join & complete surveys, task to earn points.\r \r Register to Grabpoints using full valid details and collect 2500 points.\r \r Credited within 5 minutes.",
        disclaimer: "Credited within 5 minutes.",
        payout: "1.62",
        image:
          "https://static.offertoro.com/uploads/offers_image/60ba4495e11513f85723f74b01ac007e605017fa8cfbfdbf814c00dd7c0f6891.png",
        countries: [
          "BR",
          "CL",
          "CO",
          "CR",
          "EG",
          "KE",
          "MO",
          "MX",
          "MY",
          "OM",
          "PE",
          "PH",
          "QA",
          "TH",
          "TR",
          "TW",
          "ZA",
        ],
        goals: null,
        os: "all",
        incent: "1",
        url: "https://clickwall.test/api/redirect/eyJpdiI6IkdEN0Z4ckh1MnZaNTkrT1ZhVHF1RlE9PSIsInZhbHVlIjoiVW95WUpqYlFoMzJ6Rkx2QTFuczhsSkVZVHVrZ3NGVVdEMnFMNVFnZmxFb2VtNW9ITXo3cVM1QlVnT2Jxd0tWRHB0REtOSURpZzNnZGJkQnZnaFp6QjJ4b1hvNVRpM0FicmpBSWNWWmIwK0M3QkR0emo1WjY1aTJ0L2RRMkZ4VHRXbVBVd2N1bFdGcEZuTm5vQ0hyK0dYWVNLaHNaM0Q3NXVnazM3aDc0SXdCQ2tBNjdvUGg4L0JhUElEY2h6Z3lzb3dxa21FeHoyR1NhM0tQTG95aHdBUFBEeUZCRmlyaitGTC83cmxPRDBSUGRhOVJVR2RBTzIvTFJoSFpUUkwrM0ZHN2szTGxWQUNuMDRuSEhDbDRjbzVCYTVyVUVYT3NTUmVnUHNPaDhnNTgzcHJJMlQwT25WcHpLMjNHWENHNkIwem83Q1F3bVp3cGx6encvWWFsMzk5R25ueGtDaXpEdlV0MVVnUi9IbzVkbk03Qm1Wa1d6MUp3MWp6V0lNVmR3OHZkbVFyS3M1K05uR1VlWkZjSHVlZEtPRlVDaUI3MmJUMkFqSXl1UDJpST0iLCJtYWMiOiI5ZTU0OGU4Mjk2NTg1NTYzYzMyYzBjN2QyYjRmNDczNmFhNWZjNzI0MWM5ODJiZjhiYmEwZWI2Njg1NmJjNGEzIiwidGFnIjoiIn0=",
        reward: 1620,
      },
      {
        id: 1722,
        offer_type: "Survey",
        name: "Yuno Surveys",
        instructions:
          "Complete the survey.\r \r You can complete this survey 3 times a day, everyday.",
        description:
          "Complete the survey.\r \r You can complete this survey 3 times a day, everyday.",
        short_description:
          "Complete the survey.\r \r You can complete this survey 3 times a day, everyday.",
        disclaimer: "This offer rewards within 24 hours. New users only.",
        payout: "0.39",
        image:
          "https://static.offertoro.com/uploads/offers_image/3014a77db215c44b20fcd99a445192968e70823d7a493a6e643d0da5645caf13.png",
        countries: ["EG"],
        goals: null,
        os: "all",
        incent: "1",
        url: "https://clickwall.test/api/redirect/eyJpdiI6IlNGY3krNDkxTFhDckhvL1RuWDNCWXc9PSIsInZhbHVlIjoiOXQvMmw4c0VCRUFlOUJzenozZVZXS0RQNVZHQms1cEpCU1dxYjVJUUZQUy8vSURRZUw2TTZCTEltdmJkZ3Mzbmdzb29SUkI1aUczZE5GQytSTTcveDhMeWhrRTVKRWdjNE5lejQ1SVdVOEpjMFBqbzgwRXpHeFc5dStyRGxhaklEOWMyNThTU0p3SVRHa0cwNlk5ekdsSFFEYnN0aU1TOXpZNDdmQnpuZG9lS01OOE5lSEN3L0VvbitZbkRiVWx1bFZoUTR1U0FVSGdiZ2dndmJyM3ZlbllqUzRCTkxlMVJOS1BiU1Zock91aXA2YkI0UmdkMjF6SlVmeExhSmNJM0wyYkRDRG1Ha2lHVlZ1cCtJQ1hXRjNma29MNnhvZDNNcGsra3k0aGt1Ui9MbzRNWWJKcTlzS0tOeTkreHN1MHhVU3pvL3hhVTR1QmN5TmU2UWx5cnJ3ZmdvRVVNVXMyaGh6NkRvc0NWamV0d3RucDhSUWpTeU5YcjFURERCRXpWTVE2ZGgzQXpFeFFBcWtqbmFFTFNzdz09IiwibWFjIjoiMGViZTRkZDcyNjc3ODAyMDQ3MDhiNjljMDQwN2Y1MjEwZTJjOGQzNTJhYzk4MTZhMmQ3YWQxMzY3ZmQzYzhlYSIsInRhZyI6IiJ9",
        reward: 390,
      },
    ]; // Replace with your actual data fetching logic

    // Set the dataArr once the data is fetched
    //@ts-ignore
    setDataArr(dataJ);
  }, []);
  return (
    <>
      <ButtonFilter />
      {/* <Silder /> */}
      <div className="flex flex-row flex-wrap p-4 w-full">
        {dataArr.map(
          ({ id, name, instructions, image, reward, os }: dataProps) => (
            <DrawerDemo
              key={id}
              name={name}
              instructions={instructions}
              image={image}
              reward={reward}
              os={os}
              id={id}
            />
          )
        )}
      </div>
    </>
  );
}
